# Generated by Django 4.1.3 on 2022-11-29 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('building', models.CharField(blank=True, max_length=15, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('point', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grades',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dept_name', models.ForeignKey(blank=True, db_column='dept_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uni.department')),
            ],
            options={
                'db_table': 'instructor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('tot_cred', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('dept_name', models.ForeignKey(blank=True, db_column='dept_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uni.department')),
            ],
            options={
                'db_table': 'student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('s', models.OneToOneField(db_column='s_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='uni.student')),
            ],
            options={
                'db_table': 'advisor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('time_slot_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=1)),
                ('start_hr', models.DecimalField(decimal_places=0, max_digits=2)),
                ('start_min', models.DecimalField(decimal_places=0, max_digits=2)),
                ('end_hr', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('end_min', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
            ],
            options={
                'db_table': 'time_slot',
                'managed': True,
                'unique_together': {('time_slot_id', 'day', 'start_hr', 'start_min')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('credits', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('dept_name', models.ForeignKey(blank=True, db_column='dept_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uni.department')),
            ],
            options={
                'db_table': 'course',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('building', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=7, unique=True)),
                ('capacity', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'classroom',
                'managed': True,
                'unique_together': {('building', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='uni.course')),
                ('sec_id', models.CharField(max_length=8, unique=True)),
                ('semester', models.CharField(max_length=6, unique=True)),
                ('year', models.DecimalField(decimal_places=0, max_digits=4, unique=True)),
                ('time_slot_id', models.CharField(blank=True, max_length=4, null=True)),
                ('building', models.ForeignKey(blank=True, db_column='building', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uni.classroom')),
                ('room_number', models.OneToOneField(blank=True, db_column='room_number', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uni.classroom', to_field='room_number')),
            ],
            options={
                'db_table': 'section',
                'managed': True,
                'unique_together': {('course', 'sec_id', 'semester', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.OneToOneField(db_column='ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='uni.instructor')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uni.section')),
                ('sec', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uni.section', to_field='sec_id')),
                ('semester', models.ForeignKey(db_column='semester', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uni.section', to_field='semester')),
                ('year', models.ForeignKey(db_column='year', on_delete=django.db.models.deletion.DO_NOTHING, to='uni.section', to_field='year')),
            ],
            options={
                'db_table': 'teaches',
                'managed': True,
                'unique_together': {('id', 'course', 'sec', 'semester', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.OneToOneField(db_column='ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='uni.student')),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uni.section')),
                ('sec', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uni.section', to_field='sec_id')),
                ('semester', models.ForeignKey(db_column='semester', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uni.section', to_field='semester')),
                ('year', models.ForeignKey(db_column='year', on_delete=django.db.models.deletion.DO_NOTHING, to='uni.section', to_field='year')),
            ],
            options={
                'db_table': 'takes',
                'managed': True,
                'unique_together': {('id', 'course', 'sec', 'semester', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Prereq',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='uni.course')),
                ('prereq', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uni.course')),
            ],
            options={
                'db_table': 'prereq',
                'managed': True,
                'unique_together': {('course', 'prereq')},
            },
        ),
    ]
